version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8876:80"
    container_name: rssreader_nginx
    depends_on:
      - app

  app:
    build:
        context: .
        dockerfile: _docker/app/Dockerfile
    volumes:
        - ./:/var/www
    depends_on:
      - db
    container_name: rssreader_app

  db:
    image: mysql:8.1
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
        MYSQL_DATABASE: rssreader
        MYSQL_ROOT_PASSWORD: Lclmau2
    ports:
      - "8101:3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: rssreader_db

